Issue/underscores 1836
beautify-web/js-beautify pull request #1844
Opened 2020-10-03 07:19 UTC by mrmonroe

# Description
- [x ] Source branch in your fork has meaningful name (not `master`)

Fixes Issue: 
#1836 Numbers should be allowed to contain underscores.

# Before Merge Checklist 
These items can be completed after PR is created.

(Check any items that are not applicable (NA) for this PR)

- [x] JavaScript implementation
- [x] Python implementation (NA if HTML beautifier)
- [x] Added Tests to data file(s)
- [NA] Added command-line option(s) (NA if
- [NA] README.md documents new feature/option(s)

2020-10-04 18:44 UTC, mrmonroe commented
Hey guys, 
Looks like the code climate failure is a long-standing issue as the regex line is 104 characters long. I'll be glad to break it down but not sure if you guys have been overriding it and don't want to break style or readability for the code. 

The other failures are from the ./tools/git-status-clear.sh script running in the Azure pipeline which looks like an outstanding issue, although I don't see it logged. I ran the script on my Mac and Linux boxes and have no problems with it. I'd be glad to help you guys with it but of course, I don't have access to the Azure account. 

Let me know how you want to proceed.

2020-11-07 00:07 UTC, bitwiseman commented
> Looks like the code climate failure is a long-standing issue as the regex line is 104 characters long. I'll be glad to break it down but not sure if you guys have been overriding it and don't want to break style or readability for the code. 

Please feel free to break the regex to multiple lines/variables for clarity. 

Thanks for the heads up on the CI failure, I'll look into that.

2020-11-07 00:21 UTC, bitwiseman requested changes
Please add tests as noted. 

Also, the current change only addresses `0b` numbers.  Will you be updating to handle all number forms?  If so, please include tests for similar scenarios to the ones noted for other numbers. 

Keep in mind `_` is the start of a variable name, so `._001` cannot be treated as a number during tokenizing.  It will need to be treated as `.` and a variable `_001`.  

There's a bunch of edge cases.   

Thanks for contributing this PR!

2021-03-02 02:13 UTC, mrmonroe commented
@bitwiseman been down with Covid for a long time and just getting my life back together. Will get to this PR in a few days.

2021-03-03 07:47 UTC, bitwiseman commented
@mrmonroe  
Sorry to hear that, but welcome back.  Thanks for picking this back up. Take your time.

2021-05-17 21:01 UTC, bitwiseman commented on test/data/javascript/tests.js
> +        { unchanged: 'a = 0b0_1_1_1'},
```suggestion
        { unchanged: 'a = 0b0_1_1_1' },
```

2021-05-17 21:04 UTC, bitwiseman commented on python/jsbeautifier/javascript/tokenizer.py
> +    r"0[xX][0123456789abcdefABCDEF]*|0[oO][01234567]*|0[bB][01_]*|\d+n|(?:\.\d+|\d+\.?\d*)(?:[eE][+-]?\d+)?"
```suggestion
    r"0[xX][0123456789abcdefABCDEF_]*|0[oO][01234567_]*|0[bB][01_]*|\d[\d_]*n|(?:\.\d[\d_]*|\d[\d_]*\.?[\d_]*)(?:[eE][+-]?[\d_]+)?"
```

2021-05-17 23:39 UTC, bitwiseman approved these changes

2021-05-20 20:03 UTC, merged