Add unit tests for input scanner
beautify-web/js-beautify pull request #1892
Opened 2021-03-07 09:21 UTC by athiramanu

# Description
Added unit test for remaining functions in input scanner. 
assert.equal  changed to assert.strictEqual for the existing tests in the file since it is being shown as deprecated

2021-03-10 17:12 UTC, bitwiseman commented on js/test/core/test_inputscanner.js
> +      assert.notStrictEqual(patternmatch, null);
```suggestion
      assert.notStrictEqual(patternmatch, null);
      assert.strictEqual(patternmatch[0], 'how');
```

2021-03-10 17:19 UTC, bitwiseman commented on js/test/core/test_inputscanner.js
> +      var untilAfter = false;
Add a test for the following? 

```
      var pattern = /wd/;
      var untilAfter = false;
```

2021-03-10 17:19 UTC, bitwiseman commented on js/test/core/test_inputscanner.js
> +      assert.strictEqual(patternmatch, "");
Add a test for the following?  Or is covered elsewhere? 

```
      var startPattern = /how/;
      var untilPattern = /dy/;
      var untilAfter = false;
```

2021-03-10 17:23 UTC, bitwiseman requested changes
Thanks for contributing.  Minor additional requests.

2021-03-13 13:00 UTC, athiramanu commented
Hi @bitwiseman
I have updated the tests as per review. Please let me know if any changes are required

2021-03-16 08:59 UTC, bitwiseman approved these changes
Excellent! Thanks for contributing!

2021-03-16 15:58 UTC, merged