python: fix argument parsing, missing css-beautify config option
beautify-web/js-beautify pull request #1925
Opened 2021-04-26 23:34 UTC by DanielChabrowski

# Description
- [ ] Source branch in your fork has meaningful name (not `main`)

Please do notice that the default value of `keep_quiet` is different from js-beautify as there's no option to control it and I decided not to make it - python's part of the project doesn't seem very active anyway.

Fixes Issues: 
`-n` matching incorrect option. `("--preserve**-n**ewlines")` is not a tuple but a string.
```python3
>>> '-n' in ("--preserve-newlines")
True
>>> '-n' in ("--preserve-newlines",)
False
```

missing config option appearing if there are no changes:
```
'BeautifierOptions' object has no attribute 'keep_quiet'
```

keep_quiet didn't actually quiet `beautified FILE` message

# Before Merge Checklist 
These items can be completed after PR is created.

(Check any items that are not applicable (NA) for this PR)

- [ ] JavaScript implementation
- [ ] Python implementation (NA if HTML beautifier)
- [ ] Added Tests to data file(s)
- [ ] Added command-line option(s) (NA if
- [ ] README.md documents new feature/option(s)

2021-05-04 22:22 UTC, bitwiseman requested changes
I guess there are no tests for these options? If there were, would they be broken? 😢

2021-05-04 22:22 UTC, bitwiseman commented on python/cssbeautifier/css/options.py
> +        self.keep_quiet = True
Shouldn't this default to `False`?

2021-05-05 17:43 UTC, DanielChabrowski commented
> I guess there are no tests for these options? If there were, would they be broken? cry

I ran `make pytest` and nothing broke so I guess there aren't any for python implementation.

2021-05-05 22:05 UTC, bitwiseman approved these changes
I added a test that would fail before this change.  It's not perfect but it proves this issue is fixed and tries to limit it's return.

2021-05-05 22:13 UTC, merged